#! /bin/sh
# xxx.sh start/stop/restart
NEW_PROCESS=/usr/bin/gateway.update
OLD_PROCESS=/usr/bin/gateway
TMP_PROCESS=/usr/bin/gateway.bak
#1、参数校验
if [ $# -lt 1 ]
then
	echo "必须传入start/stop/restart参数"
	exit
fi

function start_process()
{
	#新固件: /usr/bin/gateway.update  旧固件:/usr/bin/gateway
	#1、判断新固件是否存在
	if [ -e  $NEW_PROCESS ]
	then
		#2、修改旧固件名称
		mv $OLD_PROCESS $TMP_PROCESS
		#3、修改新固件名称
		mv $NEW_PROCESS $OLD_PROCESS
		#4、添加执行权限
		chmod +x $OLD_PROCESS
		#5、停止旧进程
		ps -ef | grep "$OLD_PROCESS daemon" | grep -v grep | awk '{print $1}' | xargs kill
		#6、执行程序
		$OLD_PROCESS daemon
		#7、判断执行是否正常
		if [ $? -ne 0 ]
		then
			#执行异常,回滚
			mv $OLD_PROCESS $NEW_PROCESS
			mv $TMP_PROCESS $OLD_PROCESS
		else
			rm -rf $TMP_PROCESS
		fi
	fi
}

function stop_process()
{
	ps -ef | grep "$OLD_PROCESS daemon" | grep -v grep | awk '{print $1}' | xargs kill
}

function restart_process(){
	stop_process
	start_process
}
#2、根据参数启动/停止/重启程序
case $1 in
"start")
	start_process
;;
"stop")
	stop_process
;;
"restart")
	restart_process
;;
*)
	echo "参数传入错误"
;;
esac
